stages:
    - action

access-and-pull:
  tags:
    - runner-01
  stage: action
  script:
    - sshpass -p 'tZTg@VBqdVZ*' ssh -o StrictHostKeyChecking=no root@103.75.185.190 -p 24700 "ls -la && cd source_code/bussiness-core-api/006-CoreVPS/server && git pull "
  when: manual

